// Generated by CoffeeScript 1.4.0
(function() {
  var MoscowYammerDB, couchapp, ddoc, path;

  MoscowYammerDB = "moscow_yammer";

  couchapp = require('couchapp');

  path = require('path');

  ddoc = {
    _id: "_design/" + MoscowYammerDB,
    rewrites: [
      {
        from: "/",
        to: "index.html"
      }, {
        from: "/" + MoscowYammerDB,
        to: "../../"
      }, {
        from: "/" + MoscowYammerDB + "/*",
        to: "../../*"
      }, {
        from: "/*",
        to: "*"
      }
    ]
  };

  ddoc.views = {};

  ddoc.views.groups = {
    map: function(doc) {
      if (doc.type && doc.type === "group") {
        return emit([doc.content.id], doc.content);
      }
    }
  };

  ddoc.views.users = {
    map: function(doc) {
      if (doc.type && doc.type === "user") {
        return emit([doc.content.id], doc.content);
      }
    }
  };

  ddoc.validate_doc_update = function(newDoc, oldDoc, userCtx) {
    if (newDoc._deleted === true && userCtx.roles.indexOf("_admin") === -1) {
      throw "Only admin can delete documents on this database.";
    }
  };

  couchapp.loadAttachments(ddoc, path.join(__dirname, "attachments"));

  module.exports = ddoc;

}).call(this);
